seeded labirint generotor
Alexflames/one-by-one pull request #156
Opened 2020-10-10 13:02 UTC by Artaniel

2020-10-11 10:13 UTC, Alexflames requested changes

2020-10-11 10:13 UTC, Alexflames commented on Assets/Scripts/LevelScripts/Hub/SeedInput.cs
> +    public void CancelButton() {
Cancel внутри игры не работает. В Canvas OnClick забыл назначить

2020-10-11 10:13 UTC, Alexflames commented on Assets/Scripts/LevelScripts/LabirintBuilder.cs
> +    static public int seed;
Для временной реализации сойдет. А так, в будущем надо будет в файл писать, чтобы при выходе/заходе из игры сохранялось

2020-10-11 10:13 UTC, Alexflames commented on Assets/Scripts/LevelScripts/Hub/SeedInput.cs
> +        LabirintBuilder.SetupSeed(seedInput.text);
Предлагаю еще при обычном старте игры рандомный сид ставить

2020-10-11 10:13 UTC, Alexflames commented on Assets/Scripts/LevelScripts/Hub/SeedInput.cs
> +    private void OnTriggerEnter2D(Collider2D collision)
Здесь нужна проверка, что в триггер вошел игрок

2020-10-11 10:14 UTC, Alexflames commented
И еще одна просьба: пусть установка сида не запускает игру, чтобы после выбора сида можно было выбрать локацию

2020-10-11 16:41 UTC, Artaniel commented on Assets/Scripts/Items/Container.cs
> +                    Random.InitState(LabirintBuilder.seed + transform.position.GetHashCode());
Да, надо добавлять модификатор постоянный для конкретного сундука. Позиция вроде бы детерминирована при постоянном сиде, Другого идентификатора сундука не видно.

2020-10-11 16:45 UTC, Artaniel commented on Assets/Scripts/LevelScripts/Hub/SeedInput.cs
> +    public void CancelButton() {
Да, уже чинил но забыл сцену сохранить. Поправлю.

2020-10-11 16:47 UTC, Artaniel commented on Assets/Scripts/LevelScripts/Hub/SeedInput.cs
> +        LabirintBuilder.SetupSeed(seedInput.text);
Рандомный сид сделает нам больше проблем чем решит. При перезапуске сцены например при смерти, при ctrl+R, и т.п. надо будет его обновлять. И где то обязательно что то забудем. Потому я за то чтобы с не заданным сидом все работало по старому коду.

2020-10-11 16:48 UTC, Alexflames commented on Assets/Scripts/LevelScripts/Hub/SeedInput.cs
> +        LabirintBuilder.SetupSeed(seedInput.text);
Хорошо, пока что оставим так. Потом подумаем, как лучше сделать

2020-10-13 19:57 UTC, Artaniel commented on Assets/Scripts/LevelScripts/Hub/SeedInput.cs
> +    private void OnTriggerEnter2D(Collider2D collision)
Сделано.

2020-10-13 19:57 UTC, Artaniel commented on Assets/Scripts/LevelScripts/LabirintBuilder.cs
> +    static public int seed;
Сохранение добавил.

2020-10-14 07:55 UTC, merged